<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45 to 60** minutes

In this assignment you will be performing data wrangling.

## Objectives

In this lab you will perform the following:

-   Identify duplicate values in the dataset.

-   Remove duplicate values from the dataset.

-   Identify missing values in the dataset.

-   Impute the missing values in the dataset.

-   Normalize data in the dataset.

<hr>

## Hands on Lab

Import pandas module.

In [1]:
import pandas as pd

Load the dataset into a dataframe.

In [2]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv")

## Finding duplicates

In this section you will identify duplicate values in the dataset.

 Find how many duplicate rows exist in the dataframe.

In [3]:
# your code goes here
print(f"There are {df.duplicated().sum()} duplicate rows")

There are 154 duplicate rows

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [4]:
# your code goes here
df.drop_duplicates(inplace=True)
df.shape

(11398, 85)

Verify if duplicates were actually dropped.

In [5]:
# your code goes here
print(f"Count of duplicated rows is {df.duplicated().sum()}")

Count of duplicated rows is 0

## Finding Missing values

Find the missing values for all columns.

In [6]:
# your code goes here
for column in df:
    if df[column].isnull().any():
        print(f'{column} has {df[column].isnull().sum()} null values')

OpenSource has 81 null values
Student has 51 null values
EdLevel has 112 null values
UndergradMajor has 737 null values
EduOther has 164 null values
OrgSize has 96 null values
DevType has 65 null values
YearsCode has 9 null values
Age1stCode has 13 null values
YearsCodePro has 16 null values
JobSat has 1 null values
MgrIdiot has 493 null values
MgrMoney has 497 null values
MgrWant has 493 null values
LastInt has 413 null values
FizzBuzz has 37 null values
JobFactors has 3 null values
ResumeUpdate has 39 null values
CompTotal has 809 null values
CompFreq has 206 null values
ConvertedComp has 816 null values
WorkWeekHrs has 122 null values
WorkPlan has 121 null values
WorkChallenge has 164 null values
WorkRemote has 8 null values
WorkLoc has 32 null values
ImpSyn has 5 null values
CodeRev has 1 null values
CodeRevHrs has 2426 null values
UnitTests has 29 null values
PurchaseHow has 196 null values
PurchaseWhat has 38 null values
LanguageWorkedWith has 11 null values
LanguageDesireNextYear has 134 null values
DatabaseWorkedWith has 453 null values
DatabaseDesireNextYear has 1042 null values
PlatformWorkedWith has 411 null values
PlatformDesireNextYear has 544 null values
WebFrameWorkedWith has 1393 null values
WebFrameDesireNextYear has 1617 null values
MiscTechWorkedWith has 2182 null values
MiscTechDesireNextYear has 1455 null values
DevEnviron has 29 null values
OpSys has 34 null values
Containers has 82 null values
BlockchainOrg has 2322 null values
BlockchainIs has 2610 null values
BetterLife has 98 null values
ITperson has 35 null values
OffOn has 38 null values
SocialMedia has 293 null values
Extraversion has 20 null values
ScreenName has 507 null values
SOVisit1st has 325 null values
SOVisitFreq has 5 null values
SOVisitTo has 1 null values
SOFindAnswer has 3 null values
SOTimeSaved has 50 null values
SOHowMuchTime has 1917 null values
SOAccount has 1 null values
SOPartFreq has 1128 null values
SOJobs has 6 null values
EntTeams has 5 null values
WelcomeChange has 85 null values
SONewContent has 1965 null values
Age has 287 null values
Gender has 73 null values
Trans has 123 null values
Sexuality has 542 null values
Ethnicity has 675 null values
Dependents has 140 null values
SurveyLength has 19 null values
SurveyEase has 14 null values

Find out how many rows are missing in the column 'WorkLoc'

In [7]:
# your code goes here
print(f"{df['WorkLoc'].isnull().sum()} rows are missing values in the column WorkLoc")

32 rows are missing values in the column WorkLoc

## Imputing missing values

Find the  value counts for the column WorkLoc.

In [8]:
# your code goes here
print("The value counts for work location are:")
print(df['WorkLoc'].value_counts())

The value counts for work location are:
Office                                            6806
Home                                              3589
Other place, such as a coworking space or cafe     971
Name: WorkLoc, dtype: int64

Identify the value that is most frequent (majority) in the WorkLoc column.

In [9]:
#make a note of the majority value here, for future reference
#The value that is most frequent in the Work Location column is the Office.

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [10]:
# your code goes here

most_frequent = "Office"

df["WorkLoc"].fillna(most_frequent, inplace=True)

After imputation there should ideally not be any empty rows in the WorkLoc column.

Verify if imputing was successful.

In [11]:
# your code goes here
df['WorkLoc'].isnull().values.any()
# False means there are no empty rows in the column

False

## Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq". 

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

<hr>

List out the various categories in the column 'CompFreq'

In [12]:
# your code goes here
print("The CompFreq categories are:")
df['CompFreq'].value_counts()

The CompFreq categories are:

Yearly     6073
Monthly    4788
Weekly      331
Name: CompFreq, dtype: int64

Create a new column named 'NormalizedAnnualCompensation'. Use the hint given below if needed.

Double click to see the **Hint**.

<!--

Use the below logic to arrive at the values for the column NormalizedAnnualCompensation.

If the CompFreq is Yearly then use the exising value in CompTotal
If the CompFreq is Monthly then multiply the value in CompTotal with 12 (months in an year)
If the CompFreq is Weekly then multiply the value in CompTotal with 52 (weeks in an year)

-->

In [27]:
# your code goes here
df.loc[df['CompFreq'] == 'Yearly', 'NormalizedAnnualCompensation'] = df['CompTotal']
df.loc[df['CompFreq'] == 'Monthly', 'NormalizedAnnualCompensation'] = 12 * df['CompTotal']
df.loc[df['CompFreq'] == 'Weekly', 'NormalizedAnnualCompensation'] =  52 * df['CompTotal']

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

 Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).